proxy:
  secretToken: "94341054d954108df485a86df1a57a64eb837e00abbd67ad90f5fb4f246cb79b"
auth:
  type: dummy
  dummy:
    password: 'P@ssw0rd'
  whitelist:
    users:
      - admin
      - test
      - love
  #type: ldap
  #ldap:
  #  server:
  #    address: contoso.com
  #    port: 389
  #  dn:
  #    lookup: true
  #    search:
  #      filter: '({login_attr}={login})'
  #      user: 'cn=administrator,dc=contoso,dc=com'
  #      password: 'P@ssw0rd'
  #    templates:
  #      - 'cn={username},ou=people,dc=contoso,dc=com'
  #    user:
  #      searchBase: 'ou=people,dc=contoso,dc=com'
  #      escape: False
  #      attribute: 'uid'
  #      dnAttribute: 'uid'
  #  allowedGroups:
  #    - 'cn=research,ou=teams,dc=contoso,dc=com'
  #    - 'cn=scientist,ou=teams,dc=contoso,dc=com'
singleuser:
  cpu:
    limit: .5
    guarantee: .5
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia.                                                                                                                        "
      kubespawner_override:
        image: jupyter/datascience-notebook:2343e33dec46
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/all-spark-notebook:2343e33dec46
    - display_name: "Tensorflow environment"
      description: "The Jupyter Stacks tensorflow image!"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:dd2087c75645
    - display_name: "Pyspark environment"
      description: "The Jupyter Stacks Pyspark image!"
      kubespawner_override:
        image: jupyter/pyspark-notebook:dd2087c75645
    - display_name: "Scipy environment"
      description: "The Jupyter Stacks Scopy image!"
      kubespawner_override:
        image: jupyter/scipy-notebook:dd2087c75645
  extraEnv:
    EDITOR: "vim"
  scheduling:
    podPriority:
      enabled: true
    userPlaceholder:
      enabled: true
      replicas: 3
