proxy:
  secretToken: "94341054d954108df485a86df1a57a64eb837e00abbd67ad90f5fb4f246cb79b"
ingress:
  enabled: true
  hosts:
    - jupyter1.domain.com
  tls:
    - secretName: mysecret
      hosts:
        - jupyter1.domain.com
hub:
  config:
    Authenticator:
      admin_users:
        - des
    JupyterHub:
      authenticator_class: ldapauthenticator.LDAPAuthenticator
    LDAPAuthenticator:
      allowed_groups:
        - 'cn=research,ou=teams,dc=contoso,dc=com'
        - 'cn=scientist,ou=teams,dc=contoso,dc=com'
      bind_dn_template:
        - 'cn={username},ou=people,dc=contoso,dc=com'
      escape_userdn: 'False'
      lookup_dn: 'True'
      lookup_dn_search_filter: ({login_attr}={login})
      lookup_dn_search_password: 'P@ssw0rd'
      lookup_dn_search_user: 'Administrator'
      lookup_dn_user_dn_attribute: 'cn'
      server_address: 10.10.0.243
      user_attribute: 'sAMAccountName'
      user_search_base: 'ou=people,dc=contoso,dc=com'
singleuser:
  storage:
    capacity: 2G  
  cpu:
    limit: 4
    guarantee: 1
  memory:
    limit: 2G
    guarantee: 1G    
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/minimal-notebook:2343e33dec46 
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image!"
      kubespawner_override:
        image: jupyter/minimal-notebook:2343e33dec46
    - display_name: "Tensorflow environment"
      description: "The Jupyter Stacks tensorflow image!"
      kubespawner_override:
        image: jupyter/minimal-notebook:2343e33dec46 
    - display_name: "Pyspark environment"
      description: "The Jupyter Stacks Pyspark image!"
      kubespawner_override:
        image: jupyter/minimal-notebook:2343e33dec46
    - display_name: "MinimalNB with Requirements"
      description: "The Jupyter Stacks Scopy image!"
      kubespawner_override:
        image: registry.gitlab.com/goal86sg/jupyterhub:723059a49b6b4910562f9a5f69bfc9e6de4f8153
    - display_name: "Python3.7 with Requirements"
      description: "Leverage Jupyter Notebooks with the power of your NVIDIA GPU and perform GPU calculations using Tensorflow and Pytorch it contains module and GPU-able libraries!"
      kubespawner_override:
        image: registry.gitlab.com/goal86sg/jupyterhub:73b63f5236c14dbcaa332226f4a0e82c9deb1a75
  extraEnv:
    EDITOR: "vim"
  scheduling:
    podPriority:
      enabled: true
    userPlaceholder:
      enabled: true
      replicas: 3  
